export interface ColorPalette {
  id: number;
  name: string;
  productType: string;
  preferredMode: 'light' | 'dark';
  primary: string;
  onPrimary: string;
  secondary: string;
  onSecondary: string;
  accent: string;
  onAccent: string;
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  muted: string;
  mutedForeground: string;
  border: string;
  destructive: string;
  onDestructive: string;
  ring: string;
  notes: string;
}

export const colorPalettes: ColorPalette[] = [
  // ========== ORIGINAL 12 THEMES ==========
  {
    id: 1,
    name: "SaaS General",
    productType: "SaaS",
    preferredMode: 'light',
    primary: "#2563EB",
    onPrimary: "#FFFFFF",
    secondary: "#3B82F6",
    onSecondary: "#FFFFFF",
    accent: "#EA580C",
    onAccent: "#FFFFFF",
    background: "#F8FAFC",
    foreground: "#1E293B",
    card: "#FFFFFF",
    cardForeground: "#1E293B",
    muted: "#E9EFF8",
    mutedForeground: "#64748B",
    border: "#E2E8F0",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#2563EB",
    notes: "Trust blue + orange CTA contrast"
  },
  {
    id: 2,
    name: "Micro SaaS",
    productType: "SaaS",
    preferredMode: 'light',
    primary: "#6366F1",
    onPrimary: "#FFFFFF",
    secondary: "#818CF8",
    onSecondary: "#0F172A",
    accent: "#059669",
    onAccent: "#FFFFFF",
    background: "#F5F3FF",
    foreground: "#1E1B4B",
    card: "#FFFFFF",
    cardForeground: "#1E1B4B",
    muted: "#EBEFF9",
    mutedForeground: "#64748B",
    border: "#E0E7FF",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#6366F1",
    notes: "Indigo primary + emerald CTA"
  },
  {
    id: 3,
    name: "E-commerce",
    productType: "E-commerce",
    preferredMode: 'light',
    primary: "#059669",
    onPrimary: "#FFFFFF",
    secondary: "#10B981",
    onSecondary: "#0F172A",
    accent: "#EA580C",
    onAccent: "#FFFFFF",
    background: "#ECFDF5",
    foreground: "#064E3B",
    card: "#FFFFFF",
    cardForeground: "#064E3B",
    muted: "#E8F1F3",
    mutedForeground: "#64748B",
    border: "#A7F3D0",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#059669",
    notes: "Success green + urgency orange"
  },
  {
    id: 4,
    name: "E-commerce Luxury",
    productType: "E-commerce",
    preferredMode: 'light',
    primary: "#1C1917",
    onPrimary: "#FFFFFF",
    secondary: "#44403C",
    onSecondary: "#FFFFFF",
    accent: "#A16207",
    onAccent: "#FFFFFF",
    background: "#FAFAF9",
    foreground: "#0C0A09",
    card: "#FFFFFF",
    cardForeground: "#0C0A09",
    muted: "#E8ECF0",
    mutedForeground: "#64748B",
    border: "#D6D3D1",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#1C1917",
    notes: "Premium dark + gold accent"
  },
  {
    id: 5,
    name: "B2B Service",
    productType: "Business",
    preferredMode: 'light',
    primary: "#0F172A",
    onPrimary: "#FFFFFF",
    secondary: "#334155",
    onSecondary: "#FFFFFF",
    accent: "#0369A1",
    onAccent: "#FFFFFF",
    background: "#F8FAFC",
    foreground: "#020617",
    card: "#FFFFFF",
    cardForeground: "#020617",
    muted: "#E8ECF1",
    mutedForeground: "#64748B",
    border: "#E2E8F0",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#0F172A",
    notes: "Professional navy + blue CTA"
  },
  {
    id: 6,
    name: "Financial Dashboard",
    productType: "Finance",
    preferredMode: 'dark',
    primary: "#0F172A",
    onPrimary: "#FFFFFF",
    secondary: "#1E293B",
    onSecondary: "#FFFFFF",
    accent: "#22C55E",
    onAccent: "#0F172A",
    background: "#020617",
    foreground: "#F8FAFC",
    card: "#0E1223",
    cardForeground: "#F8FAFC",
    muted: "#1A1E2F",
    mutedForeground: "#94A3B8",
    border: "#334155",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#0F172A",
    notes: "Dark bg + green positive indicators"
  },
  {
    id: 7,
    name: "Analytics Dashboard",
    productType: "Analytics",
    preferredMode: 'light',
    primary: "#1E40AF",
    onPrimary: "#FFFFFF",
    secondary: "#3B82F6",
    onSecondary: "#FFFFFF",
    accent: "#D97706",
    onAccent: "#FFFFFF",
    background: "#F8FAFC",
    foreground: "#1E3A8A",
    card: "#FFFFFF",
    cardForeground: "#1E3A8A",
    muted: "#E9EEF6",
    mutedForeground: "#64748B",
    border: "#DBEAFE",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#1E40AF",
    notes: "Blue data + amber highlights"
  },
  {
    id: 8,
    name: "Healthcare App",
    productType: "Healthcare",
    preferredMode: 'light',
    primary: "#0891B2",
    onPrimary: "#FFFFFF",
    secondary: "#22D3EE",
    onSecondary: "#0F172A",
    accent: "#059669",
    onAccent: "#FFFFFF",
    background: "#ECFEFF",
    foreground: "#164E63",
    card: "#FFFFFF",
    cardForeground: "#164E63",
    muted: "#E8F1F6",
    mutedForeground: "#64748B",
    border: "#A5F3FC",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#0891B2",
    notes: "Calm cyan + health green"
  },
  {
    id: 9,
    name: "Educational App",
    productType: "Education",
    preferredMode: 'light',
    primary: "#4F46E5",
    onPrimary: "#FFFFFF",
    secondary: "#818CF8",
    onSecondary: "#0F172A",
    accent: "#EA580C",
    onAccent: "#FFFFFF",
    background: "#EEF2FF",
    foreground: "#1E1B4B",
    card: "#FFFFFF",
    cardForeground: "#1E1B4B",
    muted: "#EBEEF8",
    mutedForeground: "#64748B",
    border: "#C7D2FE",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#4F46E5",
    notes: "Playful indigo + energetic orange"
  },
  {
    id: 10,
    name: "Creative Agency",
    productType: "Creative",
    preferredMode: 'light',
    primary: "#EC4899",
    onPrimary: "#FFFFFF",
    secondary: "#F472B6",
    onSecondary: "#0F172A",
    accent: "#0891B2",
    onAccent: "#FFFFFF",
    background: "#FDF2F8",
    foreground: "#831843",
    card: "#FFFFFF",
    cardForeground: "#831843",
    muted: "#F1EEF5",
    mutedForeground: "#64748B",
    border: "#FBCFE8",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#EC4899",
    notes: "Bold pink + cyan accent"
  },
  {
    id: 11,
    name: "Portfolio/Personal",
    productType: "Portfolio",
    preferredMode: 'light',
    primary: "#18181B",
    onPrimary: "#FFFFFF",
    secondary: "#3F3F46",
    onSecondary: "#FFFFFF",
    accent: "#2563EB",
    onAccent: "#FFFFFF",
    background: "#FAFAFA",
    foreground: "#09090B",
    card: "#FFFFFF",
    cardForeground: "#09090B",
    muted: "#E8ECF0",
    mutedForeground: "#64748B",
    border: "#E4E4E7",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#18181B",
    notes: "Monochrome + blue accent"
  },
  {
    id: 12,
    name: "Gaming",
    productType: "Entertainment",
    preferredMode: 'dark',
    primary: "#7C3AED",
    onPrimary: "#FFFFFF",
    secondary: "#A78BFA",
    onSecondary: "#0F172A",
    accent: "#F43F5E",
    onAccent: "#FFFFFF",
    background: "#0F0F23",
    foreground: "#E2E8F0",
    card: "#1E1C35",
    cardForeground: "#E2E8F0",
    muted: "#27273B",
    mutedForeground: "#94A3B8",
    border: "#4C1D95",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#7C3AED",
    notes: "Neon purple + rose action"
  },

  // ========== 30 MODERN THEMES (IDs 13-42) ==========
  {
    id: 13,
    name: "Fintech/Crypto",
    productType: "Finance",
    preferredMode: 'dark',
    primary: "#F59E0B",
    onPrimary: "#0F172A",
    secondary: "#FBBF24",
    onSecondary: "#0F172A",
    accent: "#8B5CF6",
    onAccent: "#FFFFFF",
    background: "#0F172A",
    foreground: "#F8FAFC",
    card: "#222735",
    cardForeground: "#F8FAFC",
    muted: "#272F42",
    mutedForeground: "#94A3B8",
    border: "#334155",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#F59E0B",
    notes: "Gold trust + purple tech"
  },
  {
    id: 14,
    name: "Social Media App",
    productType: "Social",
    preferredMode: 'light',
    primary: "#E11D48",
    onPrimary: "#FFFFFF",
    secondary: "#FB7185",
    onSecondary: "#0F172A",
    accent: "#2563EB",
    onAccent: "#FFFFFF",
    background: "#FFF1F2",
    foreground: "#881337",
    card: "#FFFFFF",
    cardForeground: "#881337",
    muted: "#F0ECF2",
    mutedForeground: "#64748B",
    border: "#FECDD3",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#E11D48",
    notes: "Vibrant rose + engagement blue"
  },
  {
    id: 15,
    name: "Productivity Tool",
    productType: "SaaS",
    preferredMode: 'light',
    primary: "#0D9488",
    onPrimary: "#FFFFFF",
    secondary: "#14B8A6",
    onSecondary: "#0F172A",
    accent: "#EA580C",
    onAccent: "#FFFFFF",
    background: "#F0FDFA",
    foreground: "#134E4A",
    card: "#FFFFFF",
    cardForeground: "#134E4A",
    muted: "#E8F1F4",
    mutedForeground: "#64748B",
    border: "#99F6E4",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#0D9488",
    notes: "Teal focus + action orange"
  },
  {
    id: 16,
    name: "AI/Chatbot Platform",
    productType: "Tech",
    preferredMode: 'dark',
    primary: "#7C3AED",
    onPrimary: "#FFFFFF",
    secondary: "#A78BFA",
    onSecondary: "#0F172A",
    accent: "#0891B2",
    onAccent: "#FFFFFF",
    background: "#0F172A",
    foreground: "#F8FAFC",
    card: "#1E1D35",
    cardForeground: "#F8FAFC",
    muted: "#27273B",
    mutedForeground: "#94A3B8",
    border: "#4C1D95",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#7C3AED",
    notes: "AI purple + cyan interactions"
  },
  {
    id: 17,
    name: "NFT/Web3 Platform",
    productType: "Tech",
    preferredMode: 'dark',
    primary: "#8B5CF6",
    onPrimary: "#FFFFFF",
    secondary: "#A78BFA",
    onSecondary: "#0F172A",
    accent: "#FBBF24",
    onAccent: "#0F172A",
    background: "#0F0F23",
    foreground: "#F8FAFC",
    card: "#1E1D35",
    cardForeground: "#F8FAFC",
    muted: "#27273B",
    mutedForeground: "#94A3B8",
    border: "#4C1D95",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#8B5CF6",
    notes: "Purple tech + gold value"
  },
  {
    id: 18,
    name: "Mental Health App",
    productType: "Health",
    preferredMode: 'light',
    primary: "#8B5CF6",
    onPrimary: "#FFFFFF",
    secondary: "#C4B5FD",
    onSecondary: "#0F172A",
    accent: "#059669",
    onAccent: "#FFFFFF",
    background: "#FAF5FF",
    foreground: "#4C1D95",
    card: "#FFFFFF",
    cardForeground: "#4C1D95",
    muted: "#EDEFF9",
    mutedForeground: "#64748B",
    border: "#EDE9FE",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#8B5CF6",
    notes: "Calming lavender + wellness green"
  },
  {
    id: 19,
    name: "Pet Tech App",
    productType: "Lifestyle",
    preferredMode: 'light',
    primary: "#F97316",
    onPrimary: "#0F172A",
    secondary: "#FB923C",
    onSecondary: "#0F172A",
    accent: "#2563EB",
    onAccent: "#FFFFFF",
    background: "#FFF7ED",
    foreground: "#9A3412",
    card: "#FFFFFF",
    cardForeground: "#9A3412",
    muted: "#F1F0F0",
    mutedForeground: "#64748B",
    border: "#FED7AA",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#F97316",
    notes: "Playful orange + trust blue"
  },
  {
    id: 20,
    name: "Smart Home/IoT",
    productType: "Tech",
    preferredMode: 'dark',
    primary: "#1E293B",
    onPrimary: "#FFFFFF",
    secondary: "#334155",
    onSecondary: "#FFFFFF",
    accent: "#22C55E",
    onAccent: "#0F172A",
    background: "#0F172A",
    foreground: "#F8FAFC",
    card: "#1B2336",
    cardForeground: "#F8FAFC",
    muted: "#272F42",
    mutedForeground: "#94A3B8",
    border: "#475569",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#1E293B",
    notes: "Dark tech + status green"
  },
  {
    id: 21,
    name: "EV/Charging",
    productType: "Green Tech",
    preferredMode: 'light',
    primary: "#0891B2",
    onPrimary: "#FFFFFF",
    secondary: "#22D3EE",
    onSecondary: "#0F172A",
    accent: "#16A34A",
    onAccent: "#FFFFFF",
    background: "#ECFEFF",
    foreground: "#164E63",
    card: "#FFFFFF",
    cardForeground: "#164E63",
    muted: "#E8F1F6",
    mutedForeground: "#64748B",
    border: "#A5F3FC",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#0891B2",
    notes: "Electric cyan + eco green"
  },
  {
    id: 22,
    name: "Podcast Platform",
    productType: "Media",
    preferredMode: 'dark',
    primary: "#1E1B4B",
    onPrimary: "#FFFFFF",
    secondary: "#312E81",
    onSecondary: "#FFFFFF",
    accent: "#F97316",
    onAccent: "#0F172A",
    background: "#0F0F23",
    foreground: "#F8FAFC",
    card: "#1B1B30",
    cardForeground: "#F8FAFC",
    muted: "#27273B",
    mutedForeground: "#94A3B8",
    border: "#4338CA",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#1E1B4B",
    notes: "Dark audio + warm accent"
  },
  {
    id: 23,
    name: "Dating App",
    productType: "Social",
    preferredMode: 'light',
    primary: "#E11D48",
    onPrimary: "#FFFFFF",
    secondary: "#FB7185",
    onSecondary: "#0F172A",
    accent: "#EA580C",
    onAccent: "#FFFFFF",
    background: "#FFF1F2",
    foreground: "#881337",
    card: "#FFFFFF",
    cardForeground: "#881337",
    muted: "#F0ECF2",
    mutedForeground: "#64748B",
    border: "#FECDD3",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#E11D48",
    notes: "Romantic rose + warm orange"
  },
  {
    id: 24,
    name: "Beauty/Spa/Wellness",
    productType: "Lifestyle",
    preferredMode: 'light',
    primary: "#EC4899",
    onPrimary: "#FFFFFF",
    secondary: "#F9A8D4",
    onSecondary: "#0F172A",
    accent: "#8B5CF6",
    onAccent: "#FFFFFF",
    background: "#FDF2F8",
    foreground: "#831843",
    card: "#FFFFFF",
    cardForeground: "#831843",
    muted: "#F1EEF5",
    mutedForeground: "#64748B",
    border: "#FBCFE8",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#EC4899",
    notes: "Soft pink + lavender luxury"
  },
  {
    id: 25,
    name: "Restaurant/Food",
    productType: "Food",
    preferredMode: 'light',
    primary: "#DC2626",
    onPrimary: "#FFFFFF",
    secondary: "#F87171",
    onSecondary: "#0F172A",
    accent: "#A16207",
    onAccent: "#FFFFFF",
    background: "#FEF2F2",
    foreground: "#450A0A",
    card: "#FFFFFF",
    cardForeground: "#450A0A",
    muted: "#F0EDF1",
    mutedForeground: "#64748B",
    border: "#FECACA",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#DC2626",
    notes: "Appetizing red + warm gold"
  },
  {
    id: 26,
    name: "Fitness/Gym App",
    productType: "Health",
    preferredMode: 'dark',
    primary: "#F97316",
    onPrimary: "#0F172A",
    secondary: "#FB923C",
    onSecondary: "#0F172A",
    accent: "#22C55E",
    onAccent: "#0F172A",
    background: "#1F2937",
    foreground: "#F8FAFC",
    card: "#313742",
    cardForeground: "#F8FAFC",
    muted: "#37414F",
    mutedForeground: "#94A3B8",
    border: "#374151",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#F97316",
    notes: "Energy orange + success green"
  },
  {
    id: 27,
    name: "Real Estate/Property",
    productType: "Business",
    preferredMode: 'light',
    primary: "#0F766E",
    onPrimary: "#FFFFFF",
    secondary: "#14B8A6",
    onSecondary: "#0F172A",
    accent: "#0369A1",
    onAccent: "#FFFFFF",
    background: "#F0FDFA",
    foreground: "#134E4A",
    card: "#FFFFFF",
    cardForeground: "#134E4A",
    muted: "#E8F0F3",
    mutedForeground: "#64748B",
    border: "#99F6E4",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#0F766E",
    notes: "Trust teal + professional blue"
  },
  {
    id: 28,
    name: "Travel/Tourism",
    productType: "Travel",
    preferredMode: 'light',
    primary: "#0EA5E9",
    onPrimary: "#0F172A",
    secondary: "#38BDF8",
    onSecondary: "#0F172A",
    accent: "#EA580C",
    onAccent: "#FFFFFF",
    background: "#F0F9FF",
    foreground: "#0C4A6E",
    card: "#FFFFFF",
    cardForeground: "#0C4A6E",
    muted: "#E8F2F8",
    mutedForeground: "#64748B",
    border: "#BAE6FD",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#0EA5E9",
    notes: "Sky blue + adventure orange"
  },
  {
    id: 29,
    name: "Hotel/Hospitality",
    productType: "Travel",
    preferredMode: 'light',
    primary: "#1E3A8A",
    onPrimary: "#FFFFFF",
    secondary: "#3B82F6",
    onSecondary: "#FFFFFF",
    accent: "#A16207",
    onAccent: "#FFFFFF",
    background: "#F8FAFC",
    foreground: "#1E40AF",
    card: "#FFFFFF",
    cardForeground: "#1E40AF",
    muted: "#E9EEF5",
    mutedForeground: "#64748B",
    border: "#BFDBFE",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#1E3A8A",
    notes: "Luxury navy + gold service"
  },
  {
    id: 30,
    name: "Wedding/Event",
    productType: "Lifestyle",
    preferredMode: 'light',
    primary: "#DB2777",
    onPrimary: "#FFFFFF",
    secondary: "#F472B6",
    onSecondary: "#0F172A",
    accent: "#A16207",
    onAccent: "#FFFFFF",
    background: "#FDF2F8",
    foreground: "#831843",
    card: "#FFFFFF",
    cardForeground: "#831843",
    muted: "#F0EDF4",
    mutedForeground: "#64748B",
    border: "#FBCFE8",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#DB2777",
    notes: "Romantic pink + elegant gold"
  },
  {
    id: 31,
    name: "Legal Services",
    productType: "Business",
    preferredMode: 'light',
    primary: "#1E3A8A",
    onPrimary: "#FFFFFF",
    secondary: "#1E40AF",
    onSecondary: "#FFFFFF",
    accent: "#B45309",
    onAccent: "#FFFFFF",
    background: "#F8FAFC",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    muted: "#E9EEF5",
    mutedForeground: "#64748B",
    border: "#CBD5E1",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#1E3A8A",
    notes: "Authority navy + trust gold"
  },
  {
    id: 32,
    name: "Insurance Platform",
    productType: "Finance",
    preferredMode: 'light',
    primary: "#0369A1",
    onPrimary: "#FFFFFF",
    secondary: "#0EA5E9",
    onSecondary: "#0F172A",
    accent: "#16A34A",
    onAccent: "#FFFFFF",
    background: "#F0F9FF",
    foreground: "#0C4A6E",
    card: "#FFFFFF",
    cardForeground: "#0C4A6E",
    muted: "#E7EFF5",
    mutedForeground: "#64748B",
    border: "#BAE6FD",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#0369A1",
    notes: "Security blue + protected green"
  },
  {
    id: 33,
    name: "Online Course",
    productType: "Education",
    preferredMode: 'light',
    primary: "#0D9488",
    onPrimary: "#FFFFFF",
    secondary: "#2DD4BF",
    onSecondary: "#0F172A",
    accent: "#EA580C",
    onAccent: "#FFFFFF",
    background: "#F0FDFA",
    foreground: "#134E4A",
    card: "#FFFFFF",
    cardForeground: "#134E4A",
    muted: "#E8F1F4",
    mutedForeground: "#64748B",
    border: "#5EEAD4",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#0D9488",
    notes: "Progress teal + achievement orange"
  },
  {
    id: 34,
    name: "Non-profit/Charity",
    productType: "Social",
    preferredMode: 'light',
    primary: "#0891B2",
    onPrimary: "#FFFFFF",
    secondary: "#22D3EE",
    onSecondary: "#0F172A",
    accent: "#EA580C",
    onAccent: "#FFFFFF",
    background: "#ECFEFF",
    foreground: "#164E63",
    card: "#FFFFFF",
    cardForeground: "#164E63",
    muted: "#E8F1F6",
    mutedForeground: "#64748B",
    border: "#A5F3FC",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#0891B2",
    notes: "Compassion blue + action orange"
  },
  {
    id: 35,
    name: "Music Streaming",
    productType: "Media",
    preferredMode: 'dark',
    primary: "#1E1B4B",
    onPrimary: "#FFFFFF",
    secondary: "#4338CA",
    onSecondary: "#FFFFFF",
    accent: "#22C55E",
    onAccent: "#0F172A",
    background: "#0F0F23",
    foreground: "#F8FAFC",
    card: "#1B1B30",
    cardForeground: "#F8FAFC",
    muted: "#27273B",
    mutedForeground: "#94A3B8",
    border: "#312E81",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#1E1B4B",
    notes: "Dark audio + play green"
  },
  {
    id: 36,
    name: "Video Streaming",
    productType: "Media",
    preferredMode: 'dark',
    primary: "#0F0F23",
    onPrimary: "#FFFFFF",
    secondary: "#1E1B4B",
    onSecondary: "#FFFFFF",
    accent: "#E11D48",
    onAccent: "#FFFFFF",
    background: "#000000",
    foreground: "#F8FAFC",
    card: "#0C0C0D",
    cardForeground: "#F8FAFC",
    muted: "#181818",
    mutedForeground: "#94A3B8",
    border: "#312E81",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#0F0F23",
    notes: "Cinema dark + play red"
  },
  {
    id: 37,
    name: "Job Board",
    productType: "Business",
    preferredMode: 'light',
    primary: "#0369A1",
    onPrimary: "#FFFFFF",
    secondary: "#0EA5E9",
    onSecondary: "#0F172A",
    accent: "#16A34A",
    onAccent: "#FFFFFF",
    background: "#F0F9FF",
    foreground: "#0C4A6E",
    card: "#FFFFFF",
    cardForeground: "#0C4A6E",
    muted: "#E7EFF5",
    mutedForeground: "#64748B",
    border: "#BAE6FD",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#0369A1",
    notes: "Professional blue + success green"
  },
  {
    id: 38,
    name: "Marketplace P2P",
    productType: "E-commerce",
    preferredMode: 'light',
    primary: "#7C3AED",
    onPrimary: "#FFFFFF",
    secondary: "#A78BFA",
    onSecondary: "#0F172A",
    accent: "#16A34A",
    onAccent: "#FFFFFF",
    background: "#FAF5FF",
    foreground: "#4C1D95",
    card: "#FFFFFF",
    cardForeground: "#4C1D95",
    muted: "#ECEEF9",
    mutedForeground: "#64748B",
    border: "#DDD6FE",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#7C3AED",
    notes: "Trust purple + transaction green"
  },
  {
    id: 39,
    name: "Logistics/Delivery",
    productType: "Business",
    preferredMode: 'light',
    primary: "#2563EB",
    onPrimary: "#FFFFFF",
    secondary: "#3B82F6",
    onSecondary: "#FFFFFF",
    accent: "#EA580C",
    onAccent: "#FFFFFF",
    background: "#EFF6FF",
    foreground: "#1E40AF",
    card: "#FFFFFF",
    cardForeground: "#1E40AF",
    muted: "#E9EFF8",
    mutedForeground: "#64748B",
    border: "#BFDBFE",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#2563EB",
    notes: "Tracking blue + delivery orange"
  },
  {
    id: 40,
    name: "Agriculture/Farm",
    productType: "Green Tech",
    preferredMode: 'light',
    primary: "#15803D",
    onPrimary: "#FFFFFF",
    secondary: "#22C55E",
    onSecondary: "#0F172A",
    accent: "#A16207",
    onAccent: "#FFFFFF",
    background: "#F0FDF4",
    foreground: "#14532D",
    card: "#FFFFFF",
    cardForeground: "#14532D",
    muted: "#E8F0F1",
    mutedForeground: "#64748B",
    border: "#BBF7D0",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#15803D",
    notes: "Earth green + harvest gold"
  },
  {
    id: 41,
    name: "Construction",
    productType: "Business",
    preferredMode: 'light',
    primary: "#64748B",
    onPrimary: "#FFFFFF",
    secondary: "#94A3B8",
    onSecondary: "#0F172A",
    accent: "#EA580C",
    onAccent: "#FFFFFF",
    background: "#F8FAFC",
    foreground: "#334155",
    card: "#FFFFFF",
    cardForeground: "#334155",
    muted: "#EBF0F5",
    mutedForeground: "#64748B",
    border: "#E2E8F0",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#64748B",
    notes: "Industrial grey + safety orange"
  },
  {
    id: 42,
    name: "Coworking Space",
    productType: "Business",
    preferredMode: 'light',
    primary: "#F59E0B",
    onPrimary: "#0F172A",
    secondary: "#FBBF24",
    onSecondary: "#0F172A",
    accent: "#2563EB",
    onAccent: "#FFFFFF",
    background: "#FFFBEB",
    foreground: "#78350F",
    card: "#FFFFFF",
    cardForeground: "#78350F",
    muted: "#F1F2EF",
    mutedForeground: "#64748B",
    border: "#FDE68A",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#F59E0B",
    notes: "Energetic amber + booking blue"
  },

  // ========== 18 DARK MODE THEMES (IDs 43-60) ==========
  {
    id: 43,
    name: "Cyber Security",
    productType: "Tech",
    preferredMode: 'dark',
    primary: "#00FF41",
    onPrimary: "#0F172A",
    secondary: "#0D0D0D",
    onSecondary: "#FFFFFF",
    accent: "#FF3333",
    onAccent: "#FFFFFF",
    background: "#000000",
    foreground: "#E0E0E0",
    card: "#0C130E",
    cardForeground: "#E0E0E0",
    muted: "#181818",
    mutedForeground: "#94A3B8",
    border: "#1F1F1F",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#00FF41",
    notes: "Matrix green + alert red"
  },
  {
    id: 44,
    name: "Developer Tool",
    productType: "Tech",
    preferredMode: 'dark',
    primary: "#1E293B",
    onPrimary: "#FFFFFF",
    secondary: "#334155",
    onSecondary: "#FFFFFF",
    accent: "#22C55E",
    onAccent: "#0F172A",
    background: "#0F172A",
    foreground: "#F8FAFC",
    card: "#1B2336",
    cardForeground: "#F8FAFC",
    muted: "#272F42",
    mutedForeground: "#94A3B8",
    border: "#475569",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#1E293B",
    notes: "Code dark + run green"
  },
  {
    id: 45,
    name: "Space Tech",
    productType: "Tech",
    preferredMode: 'dark',
    primary: "#F8FAFC",
    onPrimary: "#0F172A",
    secondary: "#94A3B8",
    onSecondary: "#0F172A",
    accent: "#3B82F6",
    onAccent: "#FFFFFF",
    background: "#0B0B10",
    foreground: "#F8FAFC",
    card: "#1E1E23",
    cardForeground: "#F8FAFC",
    muted: "#232328",
    mutedForeground: "#94A3B8",
    border: "#1E293B",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#F8FAFC",
    notes: "Star white + launch blue"
  },
  {
    id: 46,
    name: "Quantum Computing",
    productType: "Tech",
    preferredMode: 'dark',
    primary: "#00FFFF",
    onPrimary: "#0F172A",
    secondary: "#7B61FF",
    onSecondary: "#FFFFFF",
    accent: "#FF00FF",
    onAccent: "#FFFFFF",
    background: "#050510",
    foreground: "#E0E0FF",
    card: "#101823",
    cardForeground: "#E0E0FF",
    muted: "#1D1D28",
    mutedForeground: "#94A3B8",
    border: "#333344",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#00FFFF",
    notes: "Quantum cyan + interference purple"
  },
  {
    id: 47,
    name: "Biohacking",
    productType: "Health",
    preferredMode: 'dark',
    primary: "#FF4D4D",
    onPrimary: "#FFFFFF",
    secondary: "#4D94FF",
    onSecondary: "#FFFFFF",
    accent: "#059669",
    onAccent: "#FFFFFF",
    background: "#1C1C1E",
    foreground: "#FFFFFF",
    card: "#2C2C2E",
    cardForeground: "#FFFFFF",
    muted: "#3A3A3C",
    mutedForeground: "#98989E",
    border: "#38383A",
    destructive: "#FF3B30",
    onDestructive: "#FFFFFF",
    ring: "#FF4D4D",
    notes: "Bio red/blue + vitality green"
  },
  {
    id: 48,
    name: "Drone Fleet",
    productType: "Tech",
    preferredMode: 'dark',
    primary: "#00FF41",
    onPrimary: "#0F172A",
    secondary: "#008F11",
    onSecondary: "#FFFFFF",
    accent: "#FF3333",
    onAccent: "#FFFFFF",
    background: "#0D1117",
    foreground: "#E6EDF3",
    card: "#182424",
    cardForeground: "#E6EDF3",
    muted: "#25292F",
    mutedForeground: "#94A3B8",
    border: "#30363D",
    destructive: "#EF4444",
    onDestructive: "#FFFFFF",
    ring: "#00FF41",
    notes: "Terminal green + alert red"
  },
  {
    id: 49,
    name: "Spatial OS",
    productType: "Tech",
    preferredMode: 'dark',
    primary: "#FFFFFF",
    onPrimary: "#0F172A",
    secondary: "#E5E5E5",
    onSecondary: "#0F172A",
    accent: "#FFFFFF",
    onAccent: "#0F172A",
    background: "#888888",
    foreground: "#000000",
    card: "#999999",
    cardForeground: "#000000",
    muted: "#777777",
    mutedForeground: "#D4D4D4",
    border: "#CCCCCC",
    destructive: "#FF3B30",
    onDestructive: "#FFFFFF",
    ring: "#007AFF",
    notes: "Glass white + system blue"
  },
  {
    id: 50,
    name: "Personal Finance",
    productType: "Finance",
    preferredMode: 'dark',
    primary: "#1E40AF",
    onPrimary: "#FFFFFF",
    secondary: "#3B82F6",
    onSecondary: "#FFFFFF",
    accent: "#059669",
    onAccent: "#FFFFFF",
    background: "#0F172A",
    foreground: "#FFFFFF",
    card: "#192134",
    cardForeground: "#FFFFFF",
    muted: "#101A34",
    mutedForeground: "#94A3B8",
    border: "rgba(255,255,255,0.08)",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#1E40AF",
    notes: "Trust blue + profit green"
  },
  {
    id: 51,
    name: "Timer & Pomodoro",
    productType: "Productivity",
    preferredMode: 'dark',
    primary: "#DC2626",
    onPrimary: "#FFFFFF",
    secondary: "#EF4444",
    onSecondary: "#FFFFFF",
    accent: "#059669",
    onAccent: "#FFFFFF",
    background: "#0F172A",
    foreground: "#FFFFFF",
    card: "#192134",
    cardForeground: "#FFFFFF",
    muted: "#1F1829",
    mutedForeground: "#94A3B8",
    border: "rgba(255,255,255,0.08)",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#DC2626",
    notes: "Focus red + break green"
  },
  {
    id: 52,
    name: "Password Manager",
    productType: "Security",
    preferredMode: 'dark',
    primary: "#1E3A5F",
    onPrimary: "#FFFFFF",
    secondary: "#334155",
    onSecondary: "#FFFFFF",
    accent: "#059669",
    onAccent: "#FFFFFF",
    background: "#0F172A",
    foreground: "#FFFFFF",
    card: "#192134",
    cardForeground: "#FFFFFF",
    muted: "#10192E",
    mutedForeground: "#94A3B8",
    border: "rgba(255,255,255,0.08)",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#1E3A5F",
    notes: "Vault dark + secure green"
  },
  {
    id: 53,
    name: "Alarm & Clock",
    productType: "Productivity",
    preferredMode: 'dark',
    primary: "#D97706",
    onPrimary: "#FFFFFF",
    secondary: "#F59E0B",
    onSecondary: "#0F172A",
    accent: "#6366F1",
    onAccent: "#FFFFFF",
    background: "#0F172A",
    foreground: "#FFFFFF",
    card: "#192134",
    cardForeground: "#FFFFFF",
    muted: "#1F1E27",
    mutedForeground: "#94A3B8",
    border: "rgba(255,255,255,0.08)",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#D97706",
    notes: "Time amber + night indigo"
  },
  {
    id: 54,
    name: "Arcade Game",
    productType: "Gaming",
    preferredMode: 'dark',
    primary: "#DC2626",
    onPrimary: "#FFFFFF",
    secondary: "#2563EB",
    onSecondary: "#FFFFFF",
    accent: "#22C55E",
    onAccent: "#0F172A",
    background: "#0F172A",
    foreground: "#FFFFFF",
    card: "#192134",
    cardForeground: "#FFFFFF",
    muted: "#1F1829",
    mutedForeground: "#94A3B8",
    border: "rgba(255,255,255,0.08)",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#DC2626",
    notes: "Neon red+blue + score green"
  },
  {
    id: 55,
    name: "Photo Editor",
    productType: "Creative",
    preferredMode: 'dark',
    primary: "#7C3AED",
    onPrimary: "#FFFFFF",
    secondary: "#6366F1",
    onSecondary: "#FFFFFF",
    accent: "#0891B2",
    onAccent: "#FFFFFF",
    background: "#0F172A",
    foreground: "#FFFFFF",
    card: "#192134",
    cardForeground: "#FFFFFF",
    muted: "#171939",
    mutedForeground: "#94A3B8",
    border: "rgba(255,255,255,0.08)",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#7C3AED",
    notes: "Editor violet + filter cyan"
  },
  {
    id: 56,
    name: "Music Creator",
    productType: "Creative",
    preferredMode: 'dark',
    primary: "#7C3AED",
    onPrimary: "#FFFFFF",
    secondary: "#6366F1",
    onSecondary: "#FFFFFF",
    accent: "#22C55E",
    onAccent: "#0F172A",
    background: "#0F172A",
    foreground: "#FFFFFF",
    card: "#192134",
    cardForeground: "#FFFFFF",
    muted: "#171939",
    mutedForeground: "#94A3B8",
    border: "rgba(255,255,255,0.08)",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#7C3AED",
    notes: "Studio purple + waveform green"
  },
  {
    id: 57,
    name: "Fasting Timer",
    productType: "Health",
    preferredMode: 'dark',
    primary: "#6366F1",
    onPrimary: "#FFFFFF",
    secondary: "#4338CA",
    onSecondary: "#FFFFFF",
    accent: "#059669",
    onAccent: "#FFFFFF",
    background: "#0F172A",
    foreground: "#FFFFFF",
    card: "#192134",
    cardForeground: "#FFFFFF",
    muted: "#151D39",
    mutedForeground: "#94A3B8",
    border: "rgba(255,255,255,0.08)",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#6366F1",
    notes: "Fasting indigo + eating green"
  },
  {
    id: 58,
    name: "Code Challenge",
    productType: "Education",
    preferredMode: 'dark',
    primary: "#22C55E",
    onPrimary: "#0F172A",
    secondary: "#059669",
    onSecondary: "#FFFFFF",
    accent: "#D97706",
    onAccent: "#FFFFFF",
    background: "#0F172A",
    foreground: "#FFFFFF",
    card: "#192134",
    cardForeground: "#FFFFFF",
    muted: "#10242E",
    mutedForeground: "#94A3B8",
    border: "rgba(255,255,255,0.08)",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#22C55E",
    notes: "Code green + difficulty amber"
  },
  {
    id: 59,
    name: "VPN Privacy",
    productType: "Security",
    preferredMode: 'dark',
    primary: "#1E3A5F",
    onPrimary: "#FFFFFF",
    secondary: "#334155",
    onSecondary: "#FFFFFF",
    accent: "#22C55E",
    onAccent: "#0F172A",
    background: "#0F172A",
    foreground: "#FFFFFF",
    card: "#192134",
    cardForeground: "#FFFFFF",
    muted: "#10192E",
    mutedForeground: "#94A3B8",
    border: "rgba(255,255,255,0.08)",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#1E3A5F",
    notes: "Shield dark + connected green"
  },
  {
    id: 60,
    name: "White Noise",
    productType: "Lifestyle",
    preferredMode: 'dark',
    primary: "#475569",
    onPrimary: "#FFFFFF",
    secondary: "#334155",
    onSecondary: "#FFFFFF",
    accent: "#4338CA",
    onAccent: "#FFFFFF",
    background: "#0F172A",
    foreground: "#FFFFFF",
    card: "#192134",
    cardForeground: "#FFFFFF",
    muted: "#131B2F",
    mutedForeground: "#94A3B8",
    border: "rgba(255,255,255,0.08)",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
    ring: "#475569",
    notes: "Ambient grey + deep indigo"
  }
];

export function getPaletteById(id: number): ColorPalette | undefined {
  return colorPalettes.find(p => p.id === id);
}

export function applyPalette(palette: ColorPalette, mode: 'default' | 'light' | 'dark') {
  const root = document.documentElement;
  
  // Always apply these from palette
  root.style.setProperty('--color-primary', palette.primary);
  root.style.setProperty('--color-on-primary', palette.onPrimary);
  root.style.setProperty('--color-secondary', palette.secondary);
  root.style.setProperty('--color-on-secondary', palette.onSecondary);
  root.style.setProperty('--color-accent', palette.accent);
  root.style.setProperty('--color-on-accent', palette.onAccent);
  root.style.setProperty('--color-destructive', palette.destructive);
  root.style.setProperty('--color-on-destructive', palette.onDestructive);
  root.style.setProperty('--color-ring', palette.ring);
  
  if (mode === 'default') {
    root.style.setProperty('--color-background', palette.background);
    root.style.setProperty('--color-foreground', palette.foreground);
    root.style.setProperty('--color-card', palette.card);
    root.style.setProperty('--color-card-foreground', palette.cardForeground);
    root.style.setProperty('--color-muted', palette.muted);
    root.style.setProperty('--color-muted-foreground', palette.mutedForeground);
    root.style.setProperty('--color-border', palette.border);
  } else if (mode === 'light') {
    root.style.setProperty('--color-background', '#FFFFFF');
    root.style.setProperty('--color-foreground', '#1E293B');
    root.style.setProperty('--color-card', '#F8FAFC');
    root.style.setProperty('--color-card-foreground', '#1E293B');
    root.style.setProperty('--color-muted', '#F1F5F9');
    root.style.setProperty('--color-muted-foreground', '#64748B');
    root.style.setProperty('--color-border', '#E2E8F0');
  } else if (mode === 'dark') {
    root.style.setProperty('--color-background', '#0F172A');
    root.style.setProperty('--color-foreground', '#F8FAFC');
    root.style.setProperty('--color-card', '#1E293B');
    root.style.setProperty('--color-card-foreground', '#F8FAFC');
    root.style.setProperty('--color-muted', '#334155');
    root.style.setProperty('--color-muted-foreground', '#94A3B8');
    root.style.setProperty('--color-border', '#334155');
  }
}